CREATE DATABASE Anthology;
USE Anthology;
CREATE TABLE Users (PK_Users INTEGER(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, Email VARCHAR(320), PasswordHash VARCHAR(200));
CREATE TABLE Collections (PK_Collections INTEGER(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, CollectionName VARCHAR(320), TableName VARCHAR(320), FK_Users_Collections INTEGER(255));
CREATE TABLE Sizes (PK_Sizes INTEGER(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, TimeRecorded DATETIME, Magnitude INTEGER(255), FK_Collections_Users INTEGER(500));
CREATE TABLE Loans (PK_Loans INTEGER(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, DueDate DATE, FK_Collections_Loans INTEGER(255), FK_Users_Loans INTEGER(255), KeyInCorrespondingTable INTEGER(255), Email BOOLEAN, Push BOOLEAN)